# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.CharField(max_length=60)),
                ('cantidad', models.IntegerField()),
                ('cantidadInicial', models.IntegerField()),
                ('esUnitario', models.BooleanField(default=True)),
                ('unidades', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientePlato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChefToun.Ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('foto', models.CharField(max_length=120)),
                ('valor', models.FloatField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChefToun.Nino')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('costo', models.FloatField()),
                ('propina', models.FloatField()),
                ('horaInicio', models.TimeField()),
                ('horaFinal', models.TimeField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='tipoPlato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChefToun.TipoPlato'),
        ),
        migrations.AddField(
            model_name='ingredienteplato',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChefToun.Plato'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChefToun.Ubicacion'),
        ),
    ]
