# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChefToun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.TimeField()),
                ('horaFinal', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTipoPlato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChefToun.Horario')),
            ],
        ),
        migrations.RemoveField(
            model_name='tipoplato',
            name='horaFinal',
        ),
        migrations.RemoveField(
            model_name='tipoplato',
            name='horaInicio',
        ),
        migrations.AddField(
            model_name='horariotipoplato',
            name='tipoPlato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChefToun.TipoPlato'),
        ),
    ]
