# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChefToun', '0002_auto_20170612_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='valor',
        ),
    ]
