# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChefToun', '0003_remove_plato_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='icon',
            field=models.CharField(default='icon-default.png', max_length=200),
            preserve_default=False,
        ),
    ]
